### ISSUE TITLE
Update project: Roundup Issue Tracker

### ISSUE THREAD

**Issue by rouilj** [mahmoud/awesome-python-applications#176]
Ticket to track pull request to update info on the Roundup issue tracker.

Update the name (use full name), description, repo_url, add home_url and docs_url links.

------

## Basic info

**Application name**: Roundup Issue Tracker
**Application repo link**: http://hg.code.sf.net/p/roundup/code (with clone at https://github.com/roundup-tracker/roundup)
**Application home link**: https://www.roundup-tracker.org
**Application description**: Track issues for development/helpdesk etc via web/html, REST,, email, cli. Very configurable. Track your issues your way.

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
- [X] Well-known, or at least prominently used in an identifiable niche.
- [X] Maintained or otherwise demonstrably still functional on relevant platforms.
- [X] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

## Additional notability info

Was used for 15 years as the tracker for python.org.
Installable from pypi via pip. 20+ years of development.
Article on lwn.net for 20th anniversary release https://lwn.net/Articles/869118/
---

**Comment by mahmoud** [comment]
Thanks for the update. I've integrated those changes and updated the README :)
